title:             A programmer's hideout
email:             vangeelg@gmail.com
description:       Thoughts from the other side
author:            Giovanni Van Geel
baseurl:           ""
url:               "https://bravecobra.github.io"

# Social Profiles
twitter_username:  bravecobra
github_username:   bravecobra
facebook_username: giovanni.vangeel

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-git_metadata
